### ISSUE TITLE
Quotes in item details result in invalid item

### ISSUE THREAD

**Issue by Shinare-I** [dadus33-plugins/ChatItem#26]
If an item has " character in its name or lore text, it will result in "Invalid Item!" text on hover.

**Comment by Elikill58** [comment]
Can you show example ? For me, it works :
![image](https://user-images.githubusercontent.com/17381066/143261923-06e51449-0b01-4d2b-a06b-847d15bab238.png)

**Comment by Shinare-I** [comment]
I tested it with 3 items. All coal. Of these, only the last one worked.
Name: &5Test"
Lore: None

Name: None
Lore: &5Test"

Name: &5Test
Lore: &5Test
![Screenshot from 2021-11-24 17-10-53](https://user-images.githubusercontent.com/10176757/143264479-e133ef28-c32d-4e5f-aac0-490346244e01.png)
![Screenshot from 2021-11-24 17-16-20](https://user-images.githubusercontent.com/10176757/143264912-9c7bba29-c092-44ea-a4b1-858d14e2d417.png)
![Screenshot from 2021-11-24 17-15-12](https://user-images.githubusercontent.com/10176757/143264945-8ed17889-7ff9-4597-ad47-25462fd6fdae.png)

**Comment by Elikill58** [comment]
Seems to be fixed.
