### ISSUE TITLE
Updated to 2.0, Chat displays twice, the shortcode [i] is displayed twice and conflicting with chatcontrol pro.

### ISSUE THREAD

**Issue by TomLewis** [dadus33-plugins/ChatItem#29]
My config:
https://gist.github.com/TomLewis/bc37e793a99df9c376da76f7bdb3a613
Using paper 1.12.2 with ChatControl Pro 8.8.9.

![Screenshot 2021-11-25 at 12 11 45](https://user-images.githubusercontent.com/144046/143440190-c2d0043b-ec77-456a-a620-7a208873b4bc.png)

1. When used, a message is sent twice, one with the [i] and one with [i] and the item after it.
2. [i] is displayed before the item being shown in chat
3. There's a conflict with chatcontrol pro spam filter, Where you see that user _knoedel username being shown in <> and the item <knoe-lifter> being shown in chat, that is doing that because he's being tagged for spam by the chat plugin for spamming it over and over.
4. The cooldown is not working as they were able to just spam it.

**Comment by Elikill58** [comment]
Without ChatControl, how does it work ? Is it fine ?

In your hand, you had an item named "testitem" ?

**Comment by TomLewis** [comment]
I cant remove chatcontrol as this is my production server.

Yes in my hand I had an item called `&etestitem`

**Comment by Elikill58** [comment]
Ok, thanks. What is the plugin that edit the chat ? (the format of the chat)

**Comment by TomLewis** [comment]
Chatcontrol pro is the plugin that formats the chat! If it helps I can send you a copy on discord? Its a premium plugin but its discontinued now for Chatcontrol red, which I will be switching to at some point.

**Comment by Elikill58** [comment]
It seems continued but on mc-market. You can add me on discord: Elikill58#0743. i'm currently testing with free version.

**Comment by Elikill58** [comment]
Fixed in https://github.com/dadus33-plugins/ChatItem/commit/e18ef8a92779dc012adc2c23dcb7090954767574
