### ISSUE TITLE
TownyChat incompatibility?

### ISSUE THREAD

**Issue by Agaloth** [dadus33-plugins/ChatItem#30]
![image](https://user-images.githubusercontent.com/33335971/143770570-c2811181-fe20-463d-b665-322e8a5d5014.png)

if you are in town chat (townychat) and use [item] everyone will see the message when it's only supposed to be town members.

**Comment by Elikill58** [comment]
Should be fixed in commit https://github.com/dadus33-plugins/ChatItem/commit/5f0744dd0e971d77704e877dcaf14019b2441e82
